<x-app-layout>
    @section('css')
    @prepend('css')
    <link href="{{ asset('css/tree.css') }}" rel="stylesheet">
    @endsection
    <x-slot name="title">
        <h1 class="page-header-title">@lang('proudct.tags.title')</h1>
    </x-slot>
    <div class="row">
        <div class="col-12 col-lg-5">
            <div class="card">
                {{-- Form inputs for category title, slug --}}
                <div class="card-header">
                    <h4 class="card-title">@lang('product.tags.create.title')</h4>
                </div>
                <form action="{{ route('tag.store') }}" method="POST" data-type="ajax">
                    @csrf
                    <div class="card-body">
                        @if(count(config('app.site_locales'))>1)
                        <nav>
                            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                                @foreach (config('app.site_locales') as $code => $locale)
                                <button class="nav-link @if($loop->index == 0) active @endif" id="nav-tab-{{$code}}"
                                    data-bs-toggle="tab" data-bs-target="#nav-{{$code}}" type="button" role="tab"
                                    aria-controls="nav-{{$code}}" aria-selected="true"><span class="d-flex"><img
                                            src="{{asset($locale['flag'])}}" width="14" class="mr-2">
                                        {{$locale['label']}}</span></button>
                                @endforeach
                            </div>
                        </nav>
                        @endif
                        <div class="tab-content" id="nav-tabContent">
                            @foreach (config('app.site_locales') as $code => $locale)
                            <div class="tab-pane fade @if($loop->index == 0) active show @endif" id="nav-{{$code}}"
                                role="tabpanel" aria-labelledby="nav-tab-{{$code}}">
                                <div class="form-group mb-4 pt-5">
                                    <label for="title">@lang('tag.title')</label>
                                    <input type="text" class="form-control" name="title[{{$code}}]" id="title"
                                        value="{{old('name.'.$code)}}"
                                        placeholder="@lang('tag.title')">
                                </div>
                                <div class="form-group mb-4">
                                    <label for="slug">@lang('tag.slug')</label>
                                    <input type="text" class="form-control" id="slug" name="slug[{{$code}}]"
                                        value="{{old('slug.'.$code)}}"
                                        placeholder="@lang('product.category.slug')">
                                    <small class="form-text text-muted">@lang('subtitle.autogenerated')</small>
                                </div>
                            </div>
                            @endforeach
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="buttons d-flex justify-content-end">
                            <button type="submit"
                                class="btn btn-success">@lang('tag.action.create')</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="col-12 col-lg-7">
            <x-data-tables :table="$dataTables" :order="$dataOrder" />
        </div>
    </div>

    @section('js')
    @stack('js')
    <script src="{{ asset('js/tree.js') }}"></script>
    <script>
        $(document).ready(function() {
                $('#categoryTree').tree();
            });
    </script>
    @endsection
</x-app-layout>